Message 1:
Process exited with status 1: Traceback (most recent call last):
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/bank_churn/model_build_predict/model_build_predict_run_code.py", line 208, in <module>
    generated_code_function()
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/bank_churn/model_build_predict/model_build_predict_run_code.py", line 176, in generated_code_function
    best_model = train_and_validation_and_select_the_best_model(
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/tools/ml_tools.py", line 1341, in train_and_validation_and_select_the_best_model
    optimizer.fit(X_train, y_train)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 898, in fit
    self._run_search(evaluate_candidates)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 1422, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 875, in evaluate_candidates
    _warn_or_raise_about_fit_failures(out, self.error_score)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 414, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 75 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py", line 1208, in fit
    X, y = self._validate_data(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
    X = check_array(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/utils/validation.py", line 836, in check_array
    array = array.astype(new_dtype)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 138, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'Young'

--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py", line 1208, in fit
    X, y = self._validate_data(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
    X = check_array(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/sklearn/utils/validation.py", line 836, in check_array
    array = array.astype(new_dtype)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/azusa/anaconda3/envs/pipeline/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 138, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'Middle-aged'




